version = 0.1


[dev.deploy.parameters]
stack_name = "core-back-development"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ec647gpjuo2w"
s3_prefix = "ipv-core-back-development"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev\" VpcStackName=\"network-shared-development\""
parallel = "true"

[dev-danh.deploy.parameters]
stack_name = "core-back-dev-danh"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ec647gpjuo2w"
s3_prefix = "danh-core-back-stack"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev-danh\" VpcStackName=\"network-shared-development\""
parallel = "true"

[dev-danw.deploy.parameters]
stack_name = "core-back-dev-danw"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ec647gpjuo2w"
s3_prefix = "danw-core-back-stack"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev-danw\" VpcStackName=\"network-shared-development\""
parallel = "true"

[dev-danp.deploy.parameters]
stack_name = "core-back-dev-danp"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ec647gpjuo2w"
s3_prefix = "danp-core-back-stack"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev-danp\" VpcStackName=\"network-shared-development\""
parallel = "true"

[dev-chrisw.deploy.parameters]
stack_name = "core-back-dev-chrisw"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ec647gpjuo2w"
s3_prefix = "chrisw-core-back-stack"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev-chrisw\" VpcStackName=\"network-shared-development\""
parallel = "true"

[dev-amrits.deploy.parameters]
stack_name = "core-back-dev-amrits"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ec647gpjuo2w"
s3_prefix = "amrits-core-back-stack"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev-amrits\" VpcStackName=\"network-shared-development\""
parallel = "true"

[dev-kerrr.deploy.parameters]
stack_name = "core-back-dev-kerrr"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ec647gpjuo2w"
s3_prefix = "kerrr-core-back-stack"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev-kerrr\" VpcStackName=\"network-shared-development\""
parallel = "true"

[dev-derrenw.deploy.parameters]
stack_name = "core-back-dev-derrenw"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ec647gpjuo2w"
s3_prefix = "derrenw-core-back-stack"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev-derrenw\" VpcStackName=\"network-shared-development\""
parallel = "true"

[dev-patrickb.deploy.parameters]
stack_name = "core-back-dev-patrickb"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ec647gpjuo2w"
s3_prefix = "patrickb-core-back-stack"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev-patrickb\" VpcStackName=\"network-shared-development\""
parallel = "true"

[dev-vamh.deploy.parameters]
stack_name = "core-back-dev-vamh"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ec647gpjuo2w"
s3_prefix = "vamh-core-back-stack"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev-vamh\" VpcStackName=\"network-shared-development\""
parallel = "true"

[dev-tobys.deploy.parameters]
stack_name = "core-back-dev-tobys"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ec647gpjuo2w"
s3_prefix = "tobys-core-back-stack"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev-tobys\" VpcStackName=\"network-shared-development\""
parallel = "true"

[dev-jithinj.deploy.parameters]
stack_name = "core-back-dev-jithinj"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ec647gpjuo2w"
s3_prefix = "jithinj-core-back-stack"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev-jithinj\" VpcStackName=\"network-shared-development\""
parallel = "true"

[dev-rpayal.deploy.parameters]
stack_name = "core-back-dev-rpayal"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ec647gpjuo2w"
s3_prefix = "rpayal-core-back-stack"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev-rpayal\" VpcStackName=\"network-shared-development\""
parallel = "true"

[dev-laurencew.deploy.parameters]
stack_name = "core-back-dev-laurencew"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ec647gpjuo2w"s
s3_prefix = "laurencew-core-back-stack"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev-laurencew\" VpcStackName=\"network-shared-development\""
parallel = "true"