version = 0.1


[dev.deploy.parameters]
stack_name = "ipv-core-back-development"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ec647gpjuo2w"
s3_prefix = "ipv-core-back-development"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev\""

[dev-tomw.deploy.parameters]
stack_name = "ipv-core-back-dev-tomw"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ec647gpjuo2w"
s3_prefix = "tom-core-back-stack"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev-tomw\""

[dev-danh.deploy.parameters]
stack_name = "ipv-core-back-dev-danh"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ec647gpjuo2w"
s3_prefix = "danh-core-back-stack"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev-danh\""

[dev-danw.deploy.parameters]
stack_name = "ipv-core-back-dev-danw"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ec647gpjuo2w"
s3_prefix = "danw-core-back-stack"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev-danw\""

[dev-danp.deploy.parameters]
stack_name = "ipv-core-back-dev-danp"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ec647gpjuo2w"
s3_prefix = "danp-core-back-stack"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev-danp\""

[dev-chrisw.deploy.parameters]
stack_name = "ipv-core-back-dev-chrisw"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ec647gpjuo2w"
s3_prefix = "chrisw-core-back-stack"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev-chrisw\""

[dev-amrits.deploy.parameters]
stack_name = "ipv-core-back-dev-amrits"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ec647gpjuo2w"
s3_prefix = "amrits-core-back-stack"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev-amrits\""

[dev-lait.deploy.parameters]
stack_name = "ipv-core-back-dev-lait"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ec647gpjuo2w"
s3_prefix = "lait-core-back-stack"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev-lait\""

[dev-sunild.deploy.parameters]
stack_name = "ipv-core-back-dev-sunild"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ec647gpjuo2w"
s3_prefix = "sunild-core-back-stack"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev-sunild\""

[dev-kerrr.deploy.parameters]
stack_name = "ipv-core-back-dev-kerrr"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ec647gpjuo2w"
s3_prefix = "kerrr-core-back-stack"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev-kerrr\""

[dev-ianj.deploy.parameters]
stack_name = "ipv-core-back-dev-ianj"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ec647gpjuo2w"
s3_prefix = "ianj-core-back-stack"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev-ianj\""

[dev-derrenw.deploy.parameters]
stack_name = "ipv-core-back-dev-derrenw"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ec647gpjuo2w"
s3_prefix = "derrenw-core-back-stack"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev-derrenw\""

[dev-patrickb.deploy.parameters]
stack_name = "ipv-core-back-dev-patrickb"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ec647gpjuo2w"
s3_prefix = "patrickb-core-back-stack"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev-patrickb\""

[dev-vamh.deploy.parameters]
stack_name = "ipv-core-back-dev-vamh"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ec647gpjuo2w"
s3_prefix = "patrickb-core-back-stack"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev-vamh\""

[dev-wojciecho.deploy.parameters]
stack_name = "ipv-core-back-dev-wojciecho"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ec647gpjuo2w"
s3_prefix = "patrickb-core-back-stack"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev-wojciecho\""

[dev-aprilm.deploy.parameters]
stack_name = "ipv-core-back-dev-aprilm"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ec647gpjuo2w"
s3_prefix = "patrickb-core-back-stack"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev-aprilm\""

